# Site settings
title: Anmol Soni
email: anmol_soni@outlook.com
baseurl: ""
url: "https://anmol.phd"
description: "PhD Candidate at Maastricht University. Computaional climate economist with a background in sustainable energy and policy analysis"
tags:
  [
    "Agent-based modelling",
    "System dynamics",
    "Data analysis",
    "Data visualisation",
    "climate economics",
    "Actor strategy modelling",
    "Computational Economics",
  ]
keywords: "Anmol Soni, PhD candidate, Maastricht University, climate communication, climate economics, agent-based modeling, modeling and simulation, computational social science, natural language processing, Maastricht, Netherlands, India"



meta_author: Anmol Soni

# Google webmaster tools
google_verify: xkq7Q9-WxBSf88u_z0bJj5ud5g-H-fOyWfqeG9HK6a8
bing_verify:

# Contact form:
contact: static

disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c2c2c2
  primary-rgb: "44, 62, 80"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: AnmolSoni
  location: Let's Connect
  social: Socials
  credits: E-Mail

# Social networks usernames
social:
  - title: bluesky
    url: https://bsky.app/profile/anmol.phd
  - title: github
    url: http://github.com/SoniAnmol
  - title: linkedin
    url: http://linkedin.com/in/a-soni
  - title: researchgate
    url: https://www.researchgate.net/profile/Anmol-Soni-9

credits: <a href="mailto:anmol_soni@outlook.com" style="color:#FFC300;">anmol_soni@outlook.com </a>

# Postal address
address:
  - line: <a href="https://cal.com/anmol-soni/30min" style="color:#FFC300;">Schedule a meeting </a>

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

plugins:
  - jekyll-sitemap
